name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Racket action
        uses: Bogdanp/setup-racket@v1.9
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'current'

      - name: Install sicp language
        run: raco pkg install sicp

      - name: Build the site
        run: scribble --htmls ++xref-in setup/xref load-collections-xref  --redirect-main "https://docs.racket-lang.org/" --dest build/ src/scribble/sicp.scrbl

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/sicp
